name: Lint
on:
  push:
  pull_request:
permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install mypy
        run: pip install mypy
      - name: Install hatch-pyz dependencies
        run: pip install -r requirements.txt
      - name: Run mypy
        run: mypy src/
